<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="OrdersSoapServiceService" targetNamespace="http://business/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://business/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://business/" schemaLocation="OrdersSoapServiceService_schema1.xsd"></import>
</schema>
  </wsdl:types>
  <wsdl:message name="sayHello">
    <wsdl:part name="parameters" element="tns:sayHello">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getOrdersResponse">
    <wsdl:part name="parameters" element="tns:getOrdersResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getOrders">
    <wsdl:part name="parameters" element="tns:getOrders">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="sayHelloResponse">
    <wsdl:part name="parameters" element="tns:sayHelloResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="OrdersSoapService">
    <wsdl:operation name="getOrders">
      <wsdl:input name="getOrders" message="tns:getOrders">
    </wsdl:input>
      <wsdl:output name="getOrdersResponse" message="tns:getOrdersResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="sayHello">
      <wsdl:input name="sayHello" message="tns:sayHello">
    </wsdl:input>
      <wsdl:output name="sayHelloResponse" message="tns:sayHelloResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="OrdersSoapServiceServiceSoapBinding" type="tns:OrdersSoapService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getOrders">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getOrders">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getOrdersResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="sayHello">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="sayHello">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="sayHelloResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="OrdersSoapServiceService">
    <wsdl:port name="OrdersSoapServicePort" binding="tns:OrdersSoapServiceServiceSoapBinding">
      <soap:address location="http://localhost:9090/OrdersSoapServicePort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
