
package business.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.12.redhat-1
 * Sat Feb 16 13:46:41 PST 2019
 * Generated source version: 3.1.12.redhat-1
 */

@XmlRootElement(name = "getOrders", namespace = "http://business/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getOrders", namespace = "http://business/")

public class GetOrders {


}

